import os

ELASTIC_SEARCH_HOST = os.getenv("ELASTIC_SEARCH_HOST")
ELASTIC_SEARCH_USER = os.getenv("ELASTIC_SEARCH_USER")
ELASTIC_SEARCH_PASSWORD = os.getenv("ELASTIC_SEARCH_PASSWORD")
ELASTIC_SEARCH_INDEX_NAME = os.getenv("ELASTIC_SEARCH_INDEX_NAME")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
